# Generated by Django 2.2.7 on 2019-11-12 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_product_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='featured',
        ),
    ]
